---
- name: Create mariaDB dump directory
  ansible.builtin.file:
    path: "{{ mariadb_dump_path }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Create MariaDB dump script directory
  ansible.builtin.file:
    path: "{{ mariadb_dump_path_script }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Copy MariaDB dump script
  ansible.builtin.template:
    src: mariadb_dump_script.sh.j2
    dest: "{{ mariadb_dump_path_script }}/mariadb_dump_script.sh"
    owner: root
    group: root
    mode: "0750"

- name: Create a cron task for MariaDB dump script
  ansible.builtin.cron:
    name: dump mariadb
    minute: "22"
    hour: "12"
    user: root
    job: "{{ mariadb_dump_path_script }}/mariadb_dump_script.sh {{ item.name }}"
  with_items: "{{ mariadb_databases }}"
