---
- name: Disallow root login remotely
  ansible.builtin.command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='{{ mariadb_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Update root password for MariaDB
  ansible.builtin.command: >
    mysql -u root -NBe
    'ALTER USER "{{ mariadb_root_username }}"@"localhost"
    IDENTIFIED BY "{{ mariadb_root_password }}";'
  when: (mariadb_installed_packages | bool )or mariadb_root_password_update

- name: Copy .my.cnf with root crendetial
  ansible.builtin.template:
    src: my-root.cnf.j2
    dest: "{{ mariadb_root_home }}/.my.cnf"
    mode: "0600"
  when: (mariadb_installed_packages | bool )or mariadb_root_password_update

- name: Removes all anonymous user accounts
  ansible.builtin.mysql_user:
    name: ''
    host_all: true
    state: absent

- name: Remove test database
  ansible.builtin.mysql_db:
    name: "test"
    state: "absent"
