---
- name: Check if Mariadb is already installed.
  ansible.builtin.stat:
    path: /etc/init.d/mysql
  register: mariadb_installed

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: not mariadb_installed.stat.exists

- name: Install Pip
  ansible.builtin.package:
    name: ["python3-pip", "python3-setuptools", "python3-dev"]
    state: present

- name: Make sure pymysql is present
  ansible.builtin.pip:
    name: "PyMySQL"
    state: present
    executable: "pip3"

- name: Install MariaDB Packages
  ansible.builtin.package:
    name: "{{ mariadb_packages }}"
    state: present
  register: mariadb_deb_packages_is_installed
  notify:
    - Service started

- name: Flush Handlers
  meta: flush_handlers
