---
- name: Converge
  hosts: all

  roles:
    - role: supertarto.mariadb

  pre_tasks:

    - name: Install python3-apt
      package:
        name: "python3-apt"
        state: present

  vars:
    mariadb_use_dump_script: false

    mariadb_databases:
      - name: database1
        collation: utf8_general_ci
        encoding: utf8

    mariadb_users:
      - name: username
        host: localhost
        password: sqlpassword
        priv: "database1.*:SELECT,UPDATE"

      - name: "{{ mariadb_dump_user }}"
        host: localhost
        password: "{{ mariadb_dump_pass }}"
        priv: "*.*:SELECT,LOCK TABLES"

    mariadb_dump_user: "dumpuser"
    mariadb_dump_pass: "Dumppassword"

    mariadb_port: "3306"
