---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "thetarto/ansible-${MOLECULE_DISTRIB}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    command: /lib/systemd/systemd
    pre_build_image: true
provisioner:
  name: ansible
  logs: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
